spring:
  application:
    name: 'requester'

  jackson:
    serialization:
      indent_output: true
    default-property-inclusion: non_null

logging:
  level:
    root: info
    org:
      apache: warn
      springframework: warn
  pattern:
    console: '%clr([%date{HH:mm:ss.SSS}]){faint} %clr(%2p) %clr(%-40.40logger{36}){cyan} %m%n%wex'

responder:
  host: localhost
  port: 9899